<?php
include("../debut.php") ;
$a[] = "D Arsonval Brive";
$a[] = "Dac Reims";
$a[] = "Dac Reims*";
$a[] = "Darts Et Dactions Olympiques D";
$a[] = "Dassault Sports Suresnes";
$a[] = "Daytoursport";
$a[] = "De Stael Paris";
$a[] = "Decines Meyzieu Athletisme";
$a[] = "Decines Meyzieu Athletisme *";
$a[] = "Decines Meyzieu Athletisme*";
$a[] = "Def Endurance";
$a[] = "Deirbh Finn";
$a[] = "Delfeuille";
$a[] = "Denain Ac";
$a[] = "Deniv";
$a[] = "Dervallieres Athletique Club";
$a[] = "Des 7 Epis Saint Andre De l";
$a[] = "Descartes Lievin";
$a[] = "Diamant Athletic Club";
$a[] = "Diderot Tourlaville";
$a[] = "Die Ac";
$a[] = "Dijon Uc*";
$a[] = "Dimitile Sports Actions";
$a[] = "Dinamik Club Du Morne Vert";
$a[] = "Dinard";
$a[] = "Dole Ac";
$a[] = "Dombasle Athletisme";
$a[] = "Dominicaine a";
$a[] = "Domont Athletisme";
$a[] = "Donville Athletisme";
$a[] = "Donzenac Oxygene";
$a[] = "Dordogne Athle*";
$a[] = "Douai-Sin A *";
$a[] = "Doubs Sud Athletisme Besancon";
$a[] = "Doubs Sud Athletisme*";
$a[] = "Draguignan Uc";
$a[] = "Dreamrun";
$a[] = "Dreux Athletic Club A.";
$a[] = "Drucat Toutes Jambes";
$a[] = "Du Marais Cauffry";
$a[] = "Dynamic Aulnay Club";
$a[] = "Dynamic Sevres Athletisme";
$a[] = "Dynamic Sporting Club";
include("../fin.php") ;
 ?>