<?php
include("../debut.php") ;
$a[] = "I Cignali Sartinesi";
$a[] = "I.N.T. Evry";
$a[] = "I.P.S.A.";
$a[] = "Ibm France Paris";
$a[] = "Ill Bruche A Lingolsheim";
$a[] = "Immaculee Conception Laval";
$a[] = "Inaya Athletisme";
$a[] = "Indiv. Aquitaine";
$a[] = "Indiv. Corse";
$a[] = "Indiv. Cote-Dazur";
$a[] = "Indiv. Guyane";
$a[] = "Indiv. Ile-De-France";
$a[] = "Indiv. Nord Pas De Calais";
$a[] = "Indiv. Poitou";
$a[] = "Indiv. Pyrenees";
$a[] = "Indiv. Rhone-Alpes";
$a[] = "Individuel Ile-De-France";
$a[] = "Indre Ac *";
$a[] = "Infosport-Loiret";
$a[] = "Ing Sport";
$a[] = "Insa";
$a[] = "Inseme";
$a[] = "Instit.T. Roussel Montesson";
$a[] = "Institut Agneaux";
$a[] = "Intergeneration Runners";
$a[] = "Interpide Mornalienne";
$a[] = "Intrepide Angers";
$a[] = "Intrepide De Pre-En-Pail";
$a[] = "Intrepide Mornalienne";
$a[] = "Iroise Athletisme*";
$a[] = "Isle Athlé";
$a[] = "Ismcm/cesti";
$a[] = "Issou Running Trail";
$a[] = "Istres Sports";
$a[] = "Itec Bois Fleury";
$a[] = "Itec Boisfleury";
$a[] = "Itec Boisfleury La Tronche";
include("../fin.php") ;
 ?>